import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./contexts/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KonfHub Frontend Evaluation Task",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ContextProvider>
      <html lang="en">
        <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ContextProvider>
  );
}
